config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "staticpages#root"

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, presence: true, uniqueness: true
  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    return nil if user.nil?
    user.is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?

  private

  def require_no_user!
    redirect_to root_url if current_user
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
    redirect_to root_url
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_user!
    redirect_to new_session_url if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_no_user!

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(email: params[:email], password: params[:password])
    if @user
      login_user!(@user)
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render :new
    end
  end

  def destroy
    logout_user!
    redirect_to new_session_url
  end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def root
    render :index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user!(@user)
      flash[:notice] = "Account successfully created!"
    else
      flash.now[:alert] = "Oops, couldn't create account. Please make sure you are using a valid email and password and try again."
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type=hidden name=authenticity_token value=#{h(form_authenticity_token)}>".html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JPellPortfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Source+Sans+Pro&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto|Work+Sans|Raleway&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a72d195975.js"></script>
  </head>
  <body>
    <% if notice %>
      <%= notice %>
    <% end %>
    <% if alert %>
      <%= alert %>
    <% end %>
    <% if current_user.nil? %>
      <div class='login_div'>
        <a href="<%= new_session_url %>" class='header_login button'>Sign in</a>
        <a href="<%= new_user_url %>" class='header_sign_up_button'>Sign up</a>
      </div>
    <% else %>
      <div class='logout_div'>
        <p>User: <%= current_user.username %></p>
        <%# Logout button if theres a current_user %>
        <form action="<%= session_url(current_user.id) %>" method="post">
          <%= auth_token %>
          <input type="hidden" name="_method" value="delete">
          <input type="submit" value="Logout" id='header_logout_button'>
        </form>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_login_form.html.erb
<% action_url = action == :new ? users_url : new_session_url %>
<% submit_text = action == :new ? 'Create User' : 'Update'%>
<form action="<%= action_url %>" method="POST">
  <%= auth_token %>
  <% if action == :new %>
    <input type="email" name="user[email]" placeholder='email' value='<%= user.email %>' >
  <% end %>
  <input type="text" name="user[username]" placeholder='username' value='<%= user.username %>' required>
  <input type="password" name="user[password]" placeholder='password' required>
  <input type="password" name="user[password_confimartion]" placeholder='confirm password' required>
  <input type="submit" value="<%= submit_text %>">
</form>

app/views/staticpages/index.html.erb
<div id="root"></div>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'shared/login_form.html.erb', user: @user, action: :new %>